# fly.toml file generated for codeday-ai-bot on 2023-03-12T10:23:03+05:30

app = "codeday-ai-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true
